name = "stats-app"
main = "functions/_worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Site configuration for static assets
[site]
bucket = "./dist"

# Environment variables (set these in Cloudflare dashboard for security)
# These will be available to your Worker functions
# IMPORTANT: Do NOT commit real API keys to your repository!
# Set GROK_API_KEY in Cloudflare dashboard: Workers & Pages > Your App > Settings > Variables
[vars]
# GROK_API_KEY should be set in Cloudflare dashboard, not here
GROK_API_ENDPOINT = "https://api.x.ai/v1/chat/completions"
GROK_MODEL = "grok-4-latest"

# Build configuration
[build]
command = "npm run build"

# Routes - uncomment and update when you have a domain configured in Cloudflare
# [[routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"